version: "3"
networks:
  mongo-net:
services:
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    expose:
      - 27017
    restart: always
    networks:
      - mongo-net
    entrypoint: [ '/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0' ]
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo
    expose:
      - 27017
    restart: always
    networks:
      - mongo-net
    entrypoint: [ '/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0' ]
  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo
    expose:
      - 27017
    restart: always
    networks:
      - mongo-net
    entrypoint: [ '/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0' ]
  mongosetup:
    container_name: mongo_setup
    image: mongo
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - .:/scripts
    restart: 'no'
    networks:
      - mongo-net
    entrypoint: [ 'bash', '/scripts/mongo_setup.sh' ]
  web:
    container_name: api_authentication_service
    build: ..
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - mongosetup
    restart: always
    networks:
      - mongo-net
    ports:
      - '8000:8000'